language: node_js
install:
- yarn
node_js:
  - v11.6.0
cache:
  directories:
  - "$HOME/.yarn-cache"
script:
  - yarn test
  - NODE_ENV=production yarn predeploy
env:
  - PUBLIC_URL=https://mentors.codingcoach.io
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master